export const data = [
  {
    Date: "13/10/2020",
    Title: "first-todo",
    Description: "pick up milk",
    Completed: true,
    Canceled: true,
    Times: "3",
  },
  {
    Date: " 14/10/2020",
    Title: "second-todo",
    Description: "learn backbone",
    Completed: false,
    Canceled: false,
    Times: "1",
  },
  {
    Date: "15/10/2020",
    Title: "third-todo",
    Description: "go for a run",
    Completed: false,
    Canceled: false,
    Times: "2",
  },
  {
    Date: " 13/10/2020",
    Title: "fourth-todo",
    Description: "have a shower",
    Completed: false,
    Canceled: false,
    Times: "3",
  },
  {
    Date: " 14/10/2020",
    Title: "fifth-todo",
    Description: "cook mac and cheese",
    Completed: false,
    Canceled: false,
    Times: "1",
  },
  {
    Date: " 13/10/2020",
    Title: "sixth-todo",
    Description: "call mom",
    Completed: false,
    Canceled: false,
    Times: "1",
  },
  {
    Date: " 13/10/2020",
    Title: "seventh-todo",
    Description: "sleep",
    Completed: false,
    Canceled: false,
    Times: "0",
  },
];
